spring:
  application:
    name: config-client
  cloud:
    bus: ## 开启消息跟踪
      trace:
        enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8040/eureka
server:
  port: 8046

zzy: 777


## 刷新时，关闭安全验证
management:
  security:
    enabled: false
